### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JKeller86** [oddnetworks/oddworks#1]
We should have a roadmap within the repo that let's people know where we're headed in the coming months and years

**Comment by clarkefoley** [comment]
Good call, this was our last edit in a Google Spreadsheet: https://docs.google.com/spreadsheets/d/1J9Lw9YZJqFxd5jRDa1kvISJcBQOLUu8Z4t1wTvXLZzk/edit#gid=0

and we were also using this: https://github.com/oddnetworks/documentation/wiki/Product-Roadmap

I'm thinking a simple table is our best bet for this :+1:
