### ISSUE TITLE
Ensure JSON API responses validate against JSON API schema

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#101]
We should have specs that ensure the JSON API format is validated against their schema, which can be found here [http://jsonapi.org/schema](http://jsonapi.org/schema)

## Expected Behavior

When using JSON API middleware, validate the JSON response against the schema above.

## Current Behavior

We do not test for this.

## Possible Solution

There are a number of tools, but something like [jsonschema](https://www.npmjs.com/package/jsonschema) would work.

## Context

Improve test suite and ensure consistent responses when using JSON API middleware

**Comment by blainsmith** [comment]
I am sure we can divide and conquer this. To start we can use jsonschema that @brkattk mentioned above and write the schemas for them first. Fight. Bikeshed. Hug it out. Then start on tests.

Thoughts?

**Comment by brkattk** [comment]
we don't need to write schemas, there's [this](http://jsonapi.org/schema)

we just need to make sure every response that goes thru the jsonapi middleware conforms to that schema

**Comment by blainsmith** [comment]
Oh that's a generic JSON API schema. I thought you mean more of ensure a video has the proper attributes, meta, etc too.

**Comment by aljachimiak** [comment]
Made some headway on this issue this weekend.   

[Here is the start of it.](https://github.com/aljachimiak/oddworks/commit/cd776ea4f5d1aa8773623826d6110bb93d0d1163)

Just need to figure out where to put the tests.

-Al

**Comment by aljachimiak** [comment]
Closing, because this is definitely a thing now.
