### ISSUE TITLE
Ensure errors returned via JSON API middleware follow spec 

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#103]
When using the JSON API middleware, we should be following the proper format for [error objects](http://jsonapi.org/format/#error-objects)

## Expected Behavior
```
{
  "errors": [
    {
      "status": "404",
      "title": "Not Found",
      "detail": "Video Not Found"
    }
  ]
}
```

## Current Behavior

Current error objects are returned like so:
```js
{
  "statusCode": 404,
  "error": "Not Found"
}
```

**Comment by kixxauth** [comment]
This is fixed in #112 

The 404 error, specifically, will be an implementation bug in a server which is using Oddworks, not necessarily Oddworks itself.
