### ISSUE TITLE
Improve message for bad "include" query parameter

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#107]
When requesting a resource's included "relationships" attribute, on either a route that does not support `include` or where you have requested a non-existent relationship, the provided message should not be a javascript error message: `"Cannot read property 'rel' of undefined"`

While the 400 error is the proper status for such an event, the messaging could be better.

[Inclusion of Related Resources - jsonapi.org](http://jsonapi.org/format/#fetching-includes)

## Expected Behavior

When the route explicitly does not support `include`, the error message should say so.

When the resource does not contain a relationship of the given name, the error message should say so.

## Current Behavior

This is the current response:

```js
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Cannot read property 'rel' of undefined"
}
```

^ where `'rel'` is whatever you pass as the value of `?include=rel` 

## Steps to Reproduce (for bugs)

Request `/config?include=whatever`

## Context

Better user feedback for a 400 error.

**Comment by kixxauth** [comment]
I believe this is fixed to the extent it can be in #112 

There may still be a bug in one, or all of the supported stores which fumble when an `include = [] ` parameter is passed into a `get` query in the store. We'll need better testing to flush this out if it's the case.
