### ISSUE TITLE
links.self response to api endpoint is incorrect

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#126]
When sending a GET request to localhost:3000/api/v1/channels this is the response that is received:
````
{
  "data": [],
  "links": {
    "self": "http://localhost:3000/api/v1/api/v1/channels"
  },
  "meta": {}
}
````

## Expected Behavior
````
"links": {
    "self": "http://localhost:3000/api/v1/channels"
}
````

## Current Behavior
````
"links": {
    "self": "http://localhost:3000/api/v1/api/v1/channels"
}
````
The doubling of the `/api/v1` in the links.self is the unexpected result.

## Possible Solution
The `BASE_PREFIX` is defined [here](https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/response-json-api.js#L11).

Then the `base_url` gets `BASE_PREFIX` appended [here](https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/response-json-api.js#L115-L117).

The doubling happens when the `req.originalUrl` gets appended to the already appended `base_url` on [these lines](https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/response-json-api.js#L128-L130).

Here are a couple ways of doing it:

1. Stop appending the `BASE_PREFIX` to the  `base_url` on 115-117.   This may have unknown adverse affects.
2. Use string matching to only append the `BASE_PREFIX` if it is not in the `req.originalUrl`.  This seems a little heavy handed.

## Steps to Reproduce (for bugs)

1. send a GET request to localhost:3000/api/v1/channels 

## Context

Found this while working on the platform.

**Comment by blainsmith** [comment]
Was this the thing we resolved?

**Comment by aljachimiak** [comment]
I"m not sure.

@brkattk mentioned that he had an idea about why it was happening.  

To be clear though, this was in an endpoint prefixed by `/api/v1` set up by Kris and part of the Open Source repo.

Erik thought it may have something to do with the this repo, but I was unable to reproduce with this repo.  And I can barely reproduce it in the Other location.

**Comment by blainsmith** [comment]
What say we close for now and we can release a patch of oddworks since this is the last "bug".

**Comment by aljachimiak** [comment]
Agreed.

**Comment by aljachimiak** [comment]
Re-opening for incoming PR.

-Al

**Comment by aljachimiak** [comment]
Closing as PR #151 has merged the fix.
