### ISSUE TITLE
Configuring Redis Search Store does not pass Redis client correctly

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#127]
## Expected Behavior
Should be able to pass a Redis instance into the Redis Search store.

## Current Behavior
The Redis Search store sets `config.redis` to initialize `redis-search`, but the correct option should be `config.client` so instead it defaults and tries to connect to localhost.

## Possible Solution
https://github.com/oddnetworks/oddworks/blob/master/lib/stores/redis-search/index.js#L30

Needs to be `config.client` instead.

**Comment by brkattk** [comment]
This is the real issue: https://github.com/seipop/redis-search/blob/master/lib/search.js#L1

If you don't have redis installed on your machine, `require('redis')` will throw a ECONNREFUSED for 127.0.0.1 and the default redis port. @aljachimiak and I ran into this yesterday.

**Comment by blainsmith** [comment]
Yeah, you can override it by passing `client` to `redis-search` which our Redis Search Store isn't doing.

**Comment by kixxauth** [comment]
Adding to this issue regarding Oddworks Redis search - None of this has been tested, or even used for that matter since the push to v3.0

IMO we should get some tests in here to make sure this actually works.

// @blainsmith @pmcconnell 

I *think* this may have been blocking Patrick on the SDK development.

**Comment by pmcconnell** [comment]
I think this is unrelated to my cloudSearch issues which I resolved.

p.

**Comment by blainsmith** [comment]
Yes, I made this before I left and wanted to make a note of it before I forgot.
