### ISSUE TITLE
Loosely coupled services and components in Node.js systems

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#13]
## Background
Nearly 3 weeks ago we open sourced our over-the-top video distribution platform (Oddworks), written almost entirely in JavaScript for Node.js. Totally unrelated we simultaneously began experiencing issues with load on our main hosted service using that very same open source platform to deliver content to paying viewers. This was due to a new, and very popular TV show that launched on our hosted product. The catch was that this show was pre-recorded and made available to subscribed viewers at 9pm each night.

This scheduled release of new content to eager subscribers who were required to authenticate their devices to consume the content created a perfect storm to maximize the amount of load our systems could possibly experience. It resulted in us staying up each night to manually spin up more instances of the app and re-configure the edge cache to try to limit the damage. We eventually diagnosed the problem, and refactored the way our components and services communicated wich resulted in massive performance gains. The system is now handling the thundering herd without blinking.

The problems we diagnosed in our Node.js application and the eventual solution will be a great topic for another thread on another day (which we promise to deliver). But, we ran into another problem which we'd like to solve with your help first:

### We Need Your Help
Since the fix for our production issues meant ripping out the way our different components and services speak with one another, we now need to invent a new way for that to happen. This is actually great news, because you get to join us in debating the eventual solution! And we all know how software engineers openly and effectively debate solutions to thorny problems without trolling or flame wars, right?! ;-)

## The Problem
Anytime you're building a platform, you want to design it using loosely coupled components and services, right? We're no different. That is the end goal. For the sake of simplicity, we're not going to split hairs here, and we're going to call all our components and services just "services" from now on.

Also, a reminder, this is currently a 100% Node.js platform.

Anyway, to get loosely coupled services we need a standardized way of doing 2 things:

1. A common way to communicate between services
2. A common way of injecting dependencies into services

Here our our thoughts on these two items so far:

### Service Communication
We've been experiencing a growing love affair with pattern matching APIs. Here's the way it works: Services expose functions which attach themselves to some kind of pattern. Messages are then distributed into the system and when messages match a pattern they are routed to the matching function. Perhaps the simplest and most common example is using URL paths to route HTTP requests to controllers.

Another example I like a lot is the way [Erlang function match against parameters](http://learnyousomeerlang.com/syntax-in-functions). So, in JavaScript we might see a function like this:

```js
function greet(gender, name) {
  if (gender === 'male') {
    console.log('Hello, Mr. %s!', name);
  } else if (gender === 'female') {
    console.log('Hello, Mrs. %s!', name);
  } else {
    console.log('Hello, %s!', name);
  }
}
```

But, in Erlang, you can loosely couple several different, use case specific versions of that function using pattern matching:
```erlang
greet(male, Name) ->
  io:format("Hello, Mr. ~s!", [Name]);
greet(female, Name) ->
  io:format("Hello, Mrs. ~s!", [Name]);
greet(_, Name) ->
  io:format("Hello, ~s!", [Name]).
```

The Seneca.js framework [implements pattern matching](http://senecajs.org/get-started/) in JavaScript very well in our opinion:

```js
seneca.add({role: 'math', cmd: 'sum'}, function (msg, respond) {
  var sum = msg.left + msg.right
  respond(null, {answer: sum})
})
```

However, there are a few problems with Seneca.js that were kind of nagging us, and then a final nail in the coffin during our 2 weeks of performance issues (which we'll outline in a future blog post). In short, we wrote our own message passing and pattern matching system called Oddcast which I'll outline below.

### Dependency Injection
You can call it dependency injection, or inversion of control, or whatever. There are detailed explanations of dependency injection from [Martin Fowler](http://martinfowler.com/articles/injection.html) and [Microsoft](https://msdn.microsoft.com/en-us/library/ff921152.aspx) in a very enterprisy long method naming sort of way. But, my favorite explanation comes from [James Shore](http://www.jamesshore.com/Blog/Dependency-Injection-Demystified.html):

>Dependency injection means giving an object its instance variables. Really. That's it.

If you read that ^ article, there's really nothing more to say here about dependency injection. So, go read it.

### Message Passing and Pattern Matching with Oddcast
We think message passing the pattern matching are still the way go for loosely coupled communication between modules. To that end, we wrote a message passing and pattern matching library for Node.js called [Oddcast](https://github.com/oddnetworks/oddcast). It separates messages into 3 types of channels:

1. Event channel: Send and forget, multiple listeners.
2. Command channel: Send and forget, single handler.
3. Request channel: Send message, single handler, wait for response.

The use case for the Event and Request channels is kind of obvious, but the use case for the Command channel may not be so plain. The Command channel is for queueing up messages in a distributed queue or making state changes to a canonical datastore where the response is not important to the caller.

### Dependency Injection: The 'App' Object.
As an application initializes, the core Oddworks system would spin off several lifecycle events which services could then listen to in order to attach themselves to the application. The listeners would each be passed the application instance, which would have configs, the Oddcast bus, Express App, and various other dependencies (like database connections) attached to it.

## Example
Here is what a plugin for managing authentication information might look like:

```js
var store = require('./lib/store');
var middleware = require('./lib/middleware');
var router = require('./lib/router');

module.exports = function identityService(init) {
    // The 'afterServices' event ensures that the app configuration is loaded and
    // database services have been initialized.
    init.on('afterServices', function (app) {
        var db = store.initialize(app);

        app.API.bus.queryHandler(
            {role: 'identity', cmd: 'fetchOrganization'},
            db.fetchOrganization
        );
        app.API.bus.queryHandler(
            {role: 'identity', cmd: 'upsertOrganization'},
            db.upsertOrganization
        );
        app.API.bus.queryHandler(
            {role: 'identity', cmd: 'fetchDevice'},
            db.fetchDevice
        );
        app.API.bus.queryHandler(
            {role: 'identity', cmd: 'upsertDevice'},
            db.upsertDevice
        );
    });

    // The 'afterMiddleware' event ensures the core Express.js middleware is
    // already attached by Oddworks.
    init.on('afterMiddleware', function (app) {
        // Only attach middlware if it's configured to do so for this app.
        if (app.configs.myAuthPlugin.attachMiddleware) {
            app.API.express.use(middleware(app, {hash: 'headers.accessToken.deviceId'}));
        }
    });

    // The 'afterHTTPRoutes' event ensures the core Express.js routes for the
    // Oddworks content server have already been set, which means this
    // route will override, which is what we want.
    init.on('afterHTTPRoutes', function (app) {
        // Only attach a router if it's configured to do so for this app.
        if (app.configs.myAuthPlugin.attachRouter) {
            app.API.express.use('/identity', router(app));
        }
    });
};

```

The `app` Object passed into the initialization event handlers would have the following properties:

* __app.name__ - Name of the app from package.json
* __app.version__ - Version String of the app from package.json
* __app.appdir__ - The root directory file path of the app
* __app.environment__ - The current operating environment String
* __app.packageJSON__ - The full package.json Object
* __app.configs__ - Preloaded configuration settings.
* __app.API__ - Preloaded services (like database connections).

## Plugins as Services
In this way, the entire Oddworks platform is easily extendable by writing a service, defining patterns to match, and potentially attaching HTTP routes. Writing a plugin to customize your system should be fairly straightforward.

What do you think? Is this crazy? What are we missing?

**Comment by blainsmith** [comment]
Do you have an example of a sample implementation of that `IdentityService` and how you would attach it to a pre-existing express app?

**Comment by kixxauth** [comment]
There is one problem with loading plugins from the app. If the app loads several plugins in arbitrary order, and they all listen to the 'afterHTTPRoutes' lifecycle event, then their routes will be attached in that arbitrary order and the last one will win. This is probably not always what the developer wants.

Since the last plugin will always win, maybe the app should be able to configure itself like this:

```JS
var server = require('oddworks-server');
var cache = require('oddworks-redis-cache');
var store = require('oddworks-mongo-store');
var server = require('oddworks-express');
var credentials = require('oddworks-credentials-middleware');
var identity = require('oddworks-identity-service');
var authentication = require('oddworks-auth-service');
var catalog = require('oddworks-catalog-service');

function applicationInit(init) {
	init.load({
		'afterConfigs': [cache, store, server],
		'afterServices': [identity, authentication, catalog],
		'afterMiddleware': [credentials, authentication, identity]
	});
}

```

This way the app can define the order in which lifecycle events are fired into each plugin using the ordering implicit to the Arrays of plugins assigned to each lifecycle event.

**Comment by blainsmith** [comment]
Ahh yeah, thats why I deferred loading/attaching middleware/routes to the dev programmatically in my https://github.com/oddnetworks/odd-identity-service repo example attempt. Rather than learning new lifecycle events of a framework you just do vanilla express things. There is probably tradeoffs to both implementations tho. Maybe both are doable depending on how much control the dev wants?

**Comment by blainsmith** [comment]
However, if there is really those 3 or 6 (with `before` events) then thats pretty easily understood and and definitely gets you up and running pretty quickly.

**Comment by SegFaultx64** [comment]
Not to be *that guy* but this might be one of the use case where Node is simply not the best suited tech. This is exactly the Erlang Process Model, or the actor model which is implemented to great effect in Akka. Plus on the Akka/Scala side you would also get a lot of benefits in terms of dependency injection via the cake pattern. 

That being said I doubt you should need to rewrite your services to handle this issue, just the first thing that came to mind.

**Comment by blainsmith** [comment]
Yeah, we could write this in anything, but our first concern is adoptability. Basically, the majority of devs know JS and not Erlang. As long as we make the barrier low and easily understandable we can have massive adoptability to give everyone the power to run their own Netflix for their own video app.

**Comment by blainsmith** [comment]
Here is a quick pseudo-ish app using a variety of services we have to build a full-fledged multi-tenent server. Each of these servers are actually optional. You could run just the catalog service for a public API, or attach on the identity service to limit access by tokens and device types as well.

```js
'use strict';

const redis = require('redis-mock').createClient();
const oddcast = require('oddcast');
const express = require('express');
const bodyParser = require('bodyParser');

const bus = oddcast.bus();
const server = express();

bus.events.use({}, oddcast.inprocessTransport());
bus.commands.use({}, oddcast.inprocessTransport());
bus.requests.use({}, oddcast.inprocessTransport());

// Set up the services you want to use
const identityService = require('./services/identity');
identityService.initialize(bus, {redis: redis});

const authorizationService = require('./services/authorization');
authorizationService.initialize(bus, {redis: redis});

const catalogService = require('./services/catalog');
catalogService.initialize(bus, {redis: redis});

const eventsService = require('./services/events');
eventsService.initialize(bus, {redis: redis});

// Standard express middleware
server.use(bodyParser.urlencoded({extended: true}));
server.use(bodyParser.json());

// Decode the JWT set on the X-Access-Token header and attach to req.identity
server.use(identityService.middleware({header: 'x-access-token'}));

// Decode the JWT set on the Authorization header and attach to req.authorization
server.use(authorizationService.middleware({header: 'Authorization'}));

// Attach auth endpoints
// POST /auth/device/code
// POST /auth/user/authorize
// POST /auth/device/token
// GET /auth/user/:clientUserID/devices
// DELETE /auth/user/:clientUserID/devices/:deviceUserProfileID
server.use('/auth', authorizationService.router());

// Attach events endpoint
// POST /events
server.use('/events', eventsService.router());

// Attach catalog endpoints with specific middleware, the authorization service is passed in as middleware to protect/decorate the entities as well
// GET /videos
// GET /videos/:id
// GET /collections
// GET /collections/:id
// GET /views
// GET /views/:id
server.use(catalogService.router([
	authorizationService.verify()
]));

if (!module.parent) {
	server.listen(process.env.PORT || 3000);
}

module.exports = server;
```

**Comment by kixxauth** [comment]
@blainsmith I really like how you're keep the control of dependency injection in the application, and removing it from the plugins (an improvement over my original post).

My one concern here is that `.initialize()` is going to need to be async for many services and plugins.

So, I was thinking of stealing Enginemill's initialization loader to load a list of functions and/or modules. The nice thing about it, is that if a service's `initialize()` function returns a promise, the loader will not move ahead in the initialization process until that promise resolves. This way, when the app boots up, you can be sure you have all your database connections and whatnot ready to use:

https://github.com/kixxauth/enginemill/blob/master/index.js#L306-L453

and

https://github.com/kixxauth/enginemill/blob/master/index.js#L605-L650

**Comment by kixxauth** [comment]
BTW, it doesn't have to be the enginemill implementation (there are some opinions about how plugins are architected in there), but detecting and chaining promises is really useful.

**Comment by blainsmith** [comment]
Wonder if this is not opinionated enough or too opinionated, but we could offer a `Service` toolkit that does initializations that is essentially doing a lot of promise loading.

```js
// Set up the services you want to use
const identityService = require('./services/identity');
const authorizationService = require('./services/authorization');
const catalogService = require('./services/catalog');
const eventsService = require('./services/events');

Promise.join(
    identityService.initialize(bus, {redis: redis}),
    authorizationService.initialize(bus, {redis: redis}),
    catalogService.initialize(bus, {redis: redis}),
    eventsService.initialize(bus, {redis: redis})
  )
  .then(() => {
    // Attach middleware, routes, and start app
  });
```

**Comment by kixxauth** [comment]
Yep, basically it's as simple as that ^ :)

**Comment by blainsmith** [comment]
On the flip side oddcast could provide this initialization sequence we well.

**server.js**
```js
const bus = oddcast.bus();
const identityService = require('./services/identity');
oddcast.initialize([
  identityService({redis: redis}),
  eventService({redis: redis})
]);
```

**service.js**
```js
service = (options) => {
  this.options = options || {};

  return {
    initialize: (bus) => {
      // Attach patterns to bus here
    };
  };
```

As long as the services have a `.initalize()` method the `oddcast.initialize()` will call that internally and pass it the `bus` instance to attach its patterns to it.

**Comment by kixxauth** [comment]
My concern with oddcast doing it is that it seems like mixing of concerns.

I think it'd be cool if we ended up with a standardized plugin loader right in Oddworks

**Comment by blainsmith** [comment]
Works for me. The solution here certainly does not have be a technical one just more of a best practice and if that solution is just that Oddworks uses promises everywhere then we can make that decision.

**Comment by kixxauth** [comment]
Cool. I'm down wit dat.

**Comment by blainsmith** [comment]
So I've been noodling with the data store uses and since we are going to always assume Key/Value the implementation of those are different depending on the database being used. Each store should implement the 4 basic key/value operation patterns.

## Key/Value Patterns and Payloads
**{role: 'store', cmd: 'set'}, {type: TYPE, [id: UUID,]...}** 
This will store the `payload` object in the database. If no `id` is supplied then a UUID will be generated. The ID should never be generated by the database itself. Saving records to the database should also support the supplied indicies on initialization.

**{role: 'store', cmd: 'get'}, {type: TYPE, id: UUID}**
This will get the record with the `payload.id` from the database. Getting records based on any other property should not be allowed.

**{role: 'store', cmd: 'list'}, {type: TYPE, [index: INDEX,]...}**
This will list all the records with `payload.type`. If indicies are set up, then faster lookups can be performed. (ex. Give me all videos with organization equal to "Odd Networks") 

**{role: 'store', cmd: 'delete'}, {type: TYPE, id: UUID}**
Delete a record from the database and all indicies, if any.

## Store Initializations
```js
// Set up a store to manage the types specified
const memoryStore = require('./stores/memory');
memoryStore.initialize(bus, {
	types: [
		{name: 'collection', indicies: ['organization']},
		{name: 'video', indicies: ['organization']}
	]
});

const redisStore = require('./stores/redis');
redisStore.initialize(bus, {
	redis,
	types: [
		{name: 'organization'},
		{name: 'device', indicies: ['organization', 'deviceType']}
	]
});
```

Each of the stores will attach `queryHandler()` methods to interact with the database based on the types being sent around.

## Store Usage
This could be a little more elegant, but gets the convo going.

```js
bus.query({role: 'store', cmd: 'get'}, {type: 'video', id: 'my-unique-id'}); // This should pull from MemoryStore

bus.query({role: 'store', cmd: 'list'}, {type: 'video', index: {name: 'organization', value: 'Odd Networks'}}); // This should pull from RedisStore
```

Fore convenience each should should also support `commandHandler()` for `set` and `delete` too so the client doesn't have to wait for a response to the database operation. Basically, send it and forget!

**Comment by kixxauth** [comment]
This is great, great, great.

In the "get" and "list" queries I'd like to be able to add an "include" option in the argument payload which would lookup related entities. The "include" option would be an Array of String which indicate which types I would like to be included.

Of course, this means the API would also need to support a way to create and delete relationships:

**{role: 'store', cmd: 'setRelated'}, {type: STRING, sub: UUID, pred: TYPE, ref: UUID}**
Where the 'sub' is the UUID of the ower object, the 'pred' is the type of the owned object, and 'ref' is the UUID reference of the owned object.

So, you could say this in English as

> Collection with ID "abc-123" has Video with ID "def-456".

which would be sent as:

```js
{role: 'store', cmd: 'setRelated'}
{type: 'collection', sub: 'abc-123', pred: 'video', ref: 'def-456'}
```

It's then up to the datastore on how to implement that. Where to store it and how to index it so that the `{include: ['video']}` option will work.

Maybe not all datastore implementations implement this?

Maybe relationships should be left for another version?

**Comment by blainsmith** [comment]
That is too tightly coupled to JSON API Spec deep within the store. That should not be the responsibility of the store, but the plugin using the store (ie Catalog). Unless, of course, we are basically marrying JSON API forever. haha

**Comment by blainsmith** [comment]
We can certainly punt the **store** stuff for now and assume all services use [INSERT DB HERE] now and each service just instantiates with that client. We can then get abstracter later.

**Comment by brkattk** [comment]
FWIW, the Android framework has whats called a [ContentProvider](http://developer.android.com/reference/android/content/ContentProvider.html) to give everyone a common abstraction for accessing/manipulating data. 

At a high level, it does the same thing as what you're describing with the data store @blainsmith. Common messaging pattern (URI), common methods, provides the user a way to do whatever they want with their data, but the rest of the world gets a familiar interface to it. 

I think the data store discussion could probably be broken out from this one. Thought it would be good to see it from another perspective, though.

**Comment by brkattk** [comment]
BTW, it might be good to think how you could include the use case of using a REST API as a data store instead of Redis, so that we make sure the abstractions are good enough to cover what we need

**Comment by kixxauth** [comment]
My recommendation for `{include: ['thing']}` actually has nothing to do with JSON API, though I see how it could seem that way.

My reasoning is that most datastores may be able to optimize queries for related items dramatically more efficiently than having to stack up possibly hundreds of calls to `{cmd: 'get'}` record getter. I like @brkattk 's suggestion that we even consider the case of a REST API backing in, in which case allowing the underlying implementation to optimize fetching related items could make or break it. Not all datastore will be able optimize, but I think we should at least give them the choice.

Even very simple KV stores like redis could easily implement this by keeping a hash of relationships. There would be any performance improvements (unless someone way smarter than me figured it out better :wink: ), but at least it would give the opportunity to other database systems (like DynamoDB) to leverage its capability to get some free optimization.

**Comment by kixxauth** [comment]
Also, I think we should stick this out and get it figured out now rather than punting. I'm really looking forward to using this stuff without having to worry about coming back later to pay back technical debt. And, developers can more confidently use this system knowing there is a solid plugin/service communication understanding.

**Comment by blainsmith** [comment]
I think we are saying the same thing, but my mind went to JSON API with "include". As long as we do have indicies and now relationships that should get us what we need.

**Comment by brkattk** [comment]
This is only for your consideration, not as a suggestion as I see some downsides in it. I brought up the ContentProvider as an example of a similar interface, but also for the naming of their arguments in the different query methods . They all have `uri`, which would be our pattern to match on, but also one or more of the following: 

- values: field/column and value pairs for updates/inserts
- projection: an array of fields or columns to return
- selection: the "where" clause
- selectionArgs: the values for the "where" clause for substitution
- sortOrder: self explanatory

I realize this seems quite tied to SQL-ish things, which it probably initially was, but it can be used for any back-end.

**Comment by kixxauth** [comment]
Interesting @brkattk 

Both DynamoDB and Google Big Table have concepts matching almost 1:1 to what you listed there ^

**Comment by blainsmith** [comment]
Closing since the 2.0.0 release.
