### ISSUE TITLE
Internal Server Error on object not found

### ISSUE THREAD

**Issue by pmcconnell** [oddnetworks/oddworks#135]
The following request attempts to load a collection that does not exist:

http://content.oddworks.io/collections/0db5528d4c3c7ae4d5f24cce1c9fae51

The server will barf on this returning an internal server error.

I looked briefly at my local content service instance and the error occurs after the call to Boom.notFound in responseJsonAPI so its detecting there is no object but something after is causing an error.

**Comment by blainsmith** [comment]
Implementation issue internally. Not related to oddworks.
