### ISSUE TITLE
Error: Invalid name: "@oddnetworks/seneca-odd-entitlement"

### ISSUE THREAD

**Issue by balagcontus** [oddnetworks/oddworks#14]
Hi Team,

I got this error while installing this module in my local system. 

Error: Invalid name: "@oddnetworks/seneca-odd-entitlement"

Please give solution.

**Comment by kixxauth** [comment]
Hi @balagcontus,

What version of Node.js and NPM are you using?

It might be an issue with NPM support for namespacing.

**Comment by blainsmith** [comment]
Yes, that is usually the case with namespaced dependancies. The NPM version needs to be able to support them.

**Comment by blainsmith** [comment]
This has been fixed with the 2.0.0 update.
