### ISSUE TITLE
Transform url into sources array

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#144]
Transform `video.url` (if set) into standard `video.sources` array.

## Expected Behavior
It would be nice for videos to always have a `sources` array even if there is only one. We had a legacy format by setting just the `url`, but perhaps to keep the SDKs happy and assuming `sources` exists we should transform that.

## Current Behavior
If a video has a `url` and no `sources` it responds as such.

## Possible Solution
Transform `url` and attach it to a `sources` array for a more uniform response.

## Context
The web players can take multiple sources and play the appropriate version based on the format and the browser. It would be nice to always have `sources` available even if just a `url` is set as a shortcut.

**Comment by kixxauth** [comment]
Also, there may be an advantage to having a sources Object hash (vs an Array). That way device SDKs could be configured to get the one they need by key without having to search for and find it by some other criteria.

**Comment by blainsmith** [comment]
url is legacy. source and image arrays were agreed on in Odd 2. This was a helpful fix for current NASA data so SDKs have the expected sources array. Typed languages is easier to work with the array format which is why we chose it.

**Comment by blainsmith** [comment]
No longer needed since new data formats.
