### ISSUE TITLE
Opbeat agent is inactive due to configuration

### ISSUE THREAD

**Issue by Poopandain** [oddnetworks/oddworks#15]
Hi Team,

I had installed oddnetworks/oddworks to my localhost and when i am trying to execute nodejs index.js commend it has throw error which is Cannot find module '@oddnetworks/seneca-odd-auth

Please help me the issue.

**Comment by Poopandain** [comment]
Hi Team,

I have reinstall the nodejs and npm that issue has fixed which was posted above, But now i got issue like Opbeat agent is inactive due to configuration
2016-03-30T10:37:45.252Z r4x0c4wlzfth/1459334265242/25612/- INFO	hello	Seneca/1.4.0/r4x0c4wlzfth/1459334265242/25612/-	

Please help this issue.
Thanks in advance.

**Comment by Poopandain** [comment]
Hi Team,
Please refer the screenshot which i got error.

![screenshot_2016-03-30_16-19-27](https://cloud.githubusercontent.com/assets/18159171/14139843/404abb16-f693-11e5-999c-9f3a06d70cf3.png)

**Comment by blainsmith** [comment]
Hmm maybe we missed that in the documentation, but it is trying to connect to Elasticsearch which you need running.

**Comment by Poopandain** [comment]
How can i remove Elastic search from this module and where i can get opbeat test appid and secret ?

Can you help me ?

**Comment by kixxauth** [comment]
Unfortunately the content plugin currently will not work without elastisearch.

We are working on a new plugin interface that will make most of the components and services interchangeable and you should check that out: https://github.com/oddnetworks/oddworks/issues/13

Until this work is ready, you'll have to ignore the Opbeat warnings and make sure you have Elastisearch installed.

**Comment by Poopandian** [comment]
Hello I have installed elastic search and then i have face some issues please refer the screenshots help me the what is the configuration is missing in my app.
![screenshot_2016-03-31_12-59-44](https://cloud.githubusercontent.com/assets/12544202/14168637/017e7d74-f741-11e5-897c-7afad923573d.png)
![screenshot_2016-03-31_12-59-59](https://cloud.githubusercontent.com/assets/12544202/14168640/05b694e4-f741-11e5-9f69-6293d5200e8f.png)
![screenshot_2016-03-31_13-01-24](https://cloud.githubusercontent.com/assets/12544202/14168646/0a2cfc3e-f741-11e5-983a-bd7ff3e5928a.png)

**Comment by Poopandain** [comment]
Hi Team,

After installed elastic search using this url https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-14-04, And i am trying to use this command curl -X GET 'http://localhost:9200' but output status is "status" : 503, please help me the issue.

**Comment by blainsmith** [comment]
This has been removed from 2.0.0
