### ISSUE TITLE
Additional Media-related Properties

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#157]
For search and discovery we should consider more `collection` and `video` properties. Here is a possible solution for `genre`, `cast`, and `rating`. Adding `genre` will allow you to index and add facets to search filtering too. All of these should be optional if possible.
 
```json
{
  "id": "video-1",
  "type": "video",
  "title": "My Awesome Video",
  "genre": ["Action", "Adventure", "Comedy"],
  "releaseDate": "ISO_8601_DATE",
  "duration": 600,
  "cast": [
    {"name": "Blain Smith", "role": "Director"},
    {"name": "Blain Smith", "role": "Actor", "character": "Chief Beard Officer"},
    {"name": "Erik Straub", "role": "Producer"},
    {"name": "Patrick McConnell", "role": "Art Directory"}
  ],
  "rating": [
    {"locale": "en_US", "abbreviation": "R"},
    {"locale": "en_UK", "abbreviation": "18+"}
  ]
}
```

Overview of faceting search results: https://docs.aws.amazon.com/cloudsearch/latest/developerguide/faceting.html

**Comment by brkattk** [comment]
I think ratings would be an array of objects. Different types of media have different rating systems (TV vs Motion Picture) and different locales have different scales (EU vs US, etc).

sources:
https://en.wikipedia.org/wiki/Motion_picture_rating_system
https://en.wikipedia.org/wiki/Television_content_rating_systems

**Comment by blainsmith** [comment]
International and localization is definitely a whole can-o-worms we have yet to open, but that makes sense.

Edited the original post.

**Comment by brkattk** [comment]
FWIW [here's what YouTube does] for ratings (https://developers.google.com/youtube/2.0/reference#youtube_data_api_tag_media:rating) (granted, it's XML) 

A rating consists of a system (schema), value, and locale (?). Maybe only one of schema/locale would be necessary, as the app itself would then be responsible for choosing either the correct rating system or locale?

**Comment by brkattk** [comment]
Also worth seeing how other systems handle credits: 

- [youtube](https://developers.google.com/youtube/2.0/reference#youtube_data_api_tag_media:credit)
- themoviedb.org: http://docs.themoviedb.apiary.io/#reference/movies/movieidcredits/get http://docs.themoviedb.apiary.io/#reference/credits/creditcreditid/get

I'm cool with us keeping the `cast` shallow so long as we're not the primary source. If we're going to be the primary source, we're going to need to either store the `cast` resources separately or be able to search by a "person" somehow.
