### ISSUE TITLE
Support /collections/{collectionId}/relationships

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#158]
## Expected Behavior
In order to get fine grained control over the results from an Oddworks Collection, you should be able to do this:

- `/collections/{collectionId}/relationships/entities` Get all entities relationships from a collection.
- `/collections/{collectionId}/relationships/entities?sort=title` Get all entities relationships sorted by `data.attributes.title` in ascending order.
- `/collections/{collectionId}/relationships/entities?sort=-title` Get all entities relationships sorted by `data.attributes.title` in descending order (notice the "-" with "title").

#### See the JSON API Spec:

- http://jsonapi.org/format/#fetching-relationships
- http://jsonapi.org/format/#fetching-sorting
- http://jsonapi.org/format/#fetching-filtering

## Current Behavior
`/collections/{collectionId}/relationships` is a 404 in a standard Oddworks setup.

## Possible Solution
Short Term: Create a new controller (which only needs to be mounted on /collections/{collectionId}/relationships/{relationshipKey} for now), which get's a collection from the db by collectionId, and includes the relationships. It then filters data by relationshipKey and sorts it by the given query parameter if present in the URL query.

## Context
This is the first part of issue #64 to implement filter, sort, and paging on a collection.

**Comment by kixxauth** [comment]
Eventually, we'll need to represent this query better in the stores, since it will eventually blow up with very large collections.

**Comment by aljachimiak** [comment]
@kixxauth - looks like we may not be able to sort the relationships unless we retrieve the full objects that would come back with `?include={thingsToInclude}` query.

**Comment by kixxauth** [comment]
Yeah, @aljachimiak I think you're right, we'll need to fetch the fully hydrated objects, even if the caller did not create an ?include= parameter

http://jsonapi.org/format/#fetching-relationships

**Comment by aljachimiak** [comment]
> Applying sorting to that does require you to pull full objects, but you still cannot return the full objects to the client, only the id and type

Agreed - a sort should just return the id and type in the array.


> ?include=SOMETHING does nothing on /collections/:id/relationships/entities routes.

Looks like the spec addresses this.  If you look [4 paragraphs above this link](http://jsonapi.org/format/#fetching-sparse-fieldsets), they do provide for `?include=` on a relationships route.

I agree that client side sorting would be preferable. 

We should also consider that 
 - if we are already fetching the full objects for a sort/page, 
 - the client would need to make a second http request to get the objects
 - and we would need to fetch all the same data out a second time from the db 
if we didn't support `?include=` on the relationships routes.

**Comment by blainsmith** [comment]
@aljachimiak I think we can close this right?

**Comment by blainsmith** [comment]
Done.
