### ISSUE TITLE
Elastic search installation issue 

### ISSUE THREAD

**Issue by Poopandain** [oddnetworks/oddworks#16]
Hi Team, 

I have installed elastic search using this link "https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-14-04" and i am trying to call curl -X GET 'http://localhost:9200' but i am getting status which is 
{
  "status" : 503,
  "name" : "oddworks",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

Please help me this issue,
Thanks,

**Comment by chiefy** [comment]
@Poopandain that seems like an elasticsearch issue, check your ES logs on that box at: `/var/log/elasticsearch` and see if you can get any information on what the ES issue is.

**Comment by blainsmith** [comment]
This has been fixed with the 2.0.0 update.
