### ISSUE TITLE
response-json-api :: Remove broken relationships references

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#160]
## Expected Behavior

When a response is passed through the response-json-api middleware, and an included array exists, the middleware should strip out any references in the `relationships` hash which are not found in the included array.
## Current Behavior

Some references in the `relationships` hash remain, because of a hard to detect Array mutation error while using the `.slice()` method

https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/response-json-api.js#L69-L76
## Possible Solution

Reproduce this with solid automated tests, then find a fix.

**Comment by kixxauth** [comment]
@aljachimiak This my be relevant to your latest work testing middleware

**Comment by aljachimiak** [comment]
I'm a little concerned about inconsistent data...

Let's say we have this collection in the db:
````javascript
{
  "id": "collection-1",
  "type": "collection",
      "relationships": {
        "entities": {
          "data": [
            {
              "id": "video-1",
              "type": "video"
            },
            {
              "id": "video-2",
              "type": "video"
            },
            {
              "id": "video-3",
              "type": "video"
            }
          ]
        }
     }
}
````
...and for one reason or another `video-2` is missing.

What I think you're asking for is:
`GET` of `/collections/collection-1` to return exactly what is above.

`GET` of `/collections/collection-1?included=entities` would return:
````javascript
{
  "id": "collection-1",
  "type": "collection",
      "relationships": {
        "entities": {
          "data": [
            {
              "id": "video-1",
              "type": "video"
            },
            {
              "id": "video-3",
              "type": "video"
            }
          ]
        }
      },
      "included" : {
           // video 1 and video 3 in here
      }
}
````

The concern is that the for `collection-1`,  `body.relationships.entities.data !== body.relationships.entities.data` if `?include=entities` is present.

@brkattk may have a more nuanced take on this, but I just want to be sure this is the fix we're looking for before moving ahead.

**Comment by kixxauth** [comment]
Right.

If a resource is requested without an "include=foo" parameter, it should return all relationships it supposedly has. Clients will then request those relationships and get a 404.

However, if a resource is requested __with__ an "include=foo" parameter, then the client will expect the `"includes": []` array to contain all the items referenced in relationships. More often than not, this causes clients to experience an unexpected exception.

It's very tricky for client side programmers to architect a defensive solution to broken references within the same JSON document in the same request. It's much easier to design a defensive solution for broken references across separate requests (the second request resulting in a 404).

**Comment by pmcconnell** [comment]
reopening this one for two reasons:

1. I question this logic. It makes discovering where the error lies difficult for the client apps. Just ran across this in the CRTV roku app. A request for a collection returned no entities (all ids were incorrect) How is the dev/client app supposed to debug the issue? How is apparent there should be entities but they are bad? I would leave the incorrect data in place and let the client app handle the issue. Client apps should handle missing media objects gracefully.

2. This appears to be a bug: It fails to remove a single bad asset in an array. I created an entities relationship on a collection and added 5 correct videos and 1 with a bad id. The response contained all 6 entities

**Comment by brkattk** [comment]
This kind of goes hand-in-hand with #189

**Comment by aljachimiak** [comment]
#190 adds a few tests to test what happens with missing entities when a GET of `/collections/:id` happens.

**Comment by brkattk** [comment]
We reopened this for further discussion. 

After a chat in #general in Slack, here's a proposal:

- When `?include` parameter is not present, return the collection as you normally would.
- When using `?include={relationshipKey}[,{relationshipKey}]` or the route `/{resourceType}/{resourceId}/relationships/{relationshipKey}` and one or more related entities is not found, return `409 - Conflict` status with the following type of error:
```json
{
  "errors": [
    {
      "status": "409",
      "title": "Conflict",
      "detail": "Root resource references missing relationship(s)"
    },
    {
      "status": "410",
      "title": "Gone", 
      "detail": "No resource with id \"id-of-res\"", 
      "meta": {
        "identifier": {
          "id": "id-of-res",
          "type": "video"
        }
      }
    },
    {
      "status": "410",
      "title": "Gone", 
      "detail": "No resource with id \"id-of-res-2\"", 
      "meta": {
        "identifier": {
          "id": "id-of-res-2",
          "type": "video"
        }
      }
    }
  ]
}
```

**Comment by brkattk** [comment]
Important to note that the main response would be `409 - Conflict`, which is supposed to include enough information for the user to correct the issue, hence adding the `410` errors in the response body.

**Comment by pmcconnell** [comment]
will correct resources be returned? or complete fail regardless?

I would argue for returning what is possible but that may conflict with the 409? or is 409 specific enough that we can treat it as partial success?

otherwise the concept is solid

**Comment by brkattk** [comment]
`errors` can't exist in a body with a status of `20x`, so no.

**Comment by brkattk** [comment]
`The members data and errors MUST NOT coexist in the same document.`

**Comment by pmcconnell** [comment]
so if you try to view a collection and one member in 20 is missing you can't see anything?

I totally understand the spec but thats not optimal

**Comment by blainsmith** [comment]
Correct. Bad data is bad data.

**Comment by brkattk** [comment]
You can still request the collection w/o the `included` and get back the data. The server would return an error if you tried to directly access it's related data (where a bad reference exists), though.

**Comment by brkattk** [comment]
If we get on top of this now, before there are many client-side apps we can set expectations so they handle this properly. We can sort-of prevent bad data with the dashboard, but can't really make any guarantees when people set up their own servers.

**Comment by pmcconnell** [comment]
sure but then you're asking for the clients to do much more work to work around these issues. if the idea is to help the clients by avoiding sending bad data than I'm sure we're helping the clients

I think if I was starting a new client I would never use `included` and let the errors trickle down for discovery

I get it. Just wish there was an optimal way to handle this

**Comment by aljachimiak** [comment]
Note for the future:  When deleting an item, we would have to be careful to ensure that it is also removed from any parent items that it is related to.

Example:  If a video is deleted, it would need to be removed from the any collections or views that it is related to.

**Comment by blainsmith** [comment]
Yeah, we cannot force clients to use `?include` so this was the optimal way to handle this by follow the spec and informing clients using the SDK that this is the expectations when fetching using the 2 methods.

Or we write a new spec. JSON-API-Media Spec ;-)

**Comment by pmcconnell** [comment]
I already have enough issues with authority. specs are not my thing. anarchy roolz

**Comment by blainsmith** [comment]
![](https://3.bp.blogspot.com/-_USZluaRImk/VPZqJvGNlYI/AAAAAAAAS7g/TjMsLi1NiGs/s1600/Screen%2BShot%2B2015-03-03%2Bat%2B9.00.50%2BPM.jpg)

**Comment by brkattk** [comment]
issues/160#issuecomment-251174417

^ I think we've come to a consensus that this is the correct way with one notable change:

409 is a Client Error. We should replace that with a generic 500 Internal server error. 

Also, there should be an environment flag we can set on the server `FAIL_ON_MISSING_RESOURCE` which can be `true` or `false`.

- when `false` or not set, we should simply remove the missing resources from the response like we're currently doing
- when `true` we should handle the errors as described below:

- When `?include` parameter is not present, return the collection as you normally would.
- When using `?include={relationshipKey}[,{relationshipKey}]` or the route `/{resourceType}/{resourceId}/relationships/{relationshipKey}` and one or more related entities is not found, return `500 - Internal Server Error` status with the following type of error:

```
{
  "errors": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "detail": "Root resource references missing relationship(s)"
    },
    {
      "status": "410",
      "title": "Gone", 
      "detail": "No \"video\" resource with id \"id-of-res\"", 
      "meta": {
        "identifier": {
          "id": "id-of-res",
          "type": "video"
        }
      }
    },
    {
      "status": "410",
      "title": "Gone", 
      "detail": "No \"video\" resource with id \"id-of-res-2\"", 
      "meta": {
        "identifier": {
          "id": "id-of-res-2",
          "type": "video"
        }
      }
    }
  ]
}
```
