### ISSUE TITLE
Cannot update Lodash to 4.x because of peer dependency

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#166]
__npm report:__

```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package lodash@4.15.0 does not satisfy its siblings' peerDependencies requirements!
```

After some investigation, I discovered this is caused by mock-express-request and mock-express-response.

**Comment by aljachimiak** [comment]
@kixxauth - did you take care of this over the weekend?

**Comment by kixxauth** [comment]
Yeah, the peer dependency issues should be taken care of in Oddworks (lodash)
