### ISSUE TITLE
Tests do not run with Jasmine update to 2.5.0

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#167]
Tried updating Jasmine to 2.5.0 from 2.4.x and the tests simply would not run.

**Comment by thisgeek** [comment]
Works with Jasmine 2.5.2. I'll bet jasmine/jasmine-npm#88 was the problem.

**Comment by blainsmith** [comment]
Thanks @thisgeek! We will test that version and see how it goes.
