### ISSUE TITLE
Reference error: "Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#172]
```
TypeError: Cannot read property 'id' of undefined
at /app/node_modules/@oddnetworks/oddworks/lib/services/identity/controllers/identity-config-controller.js:26:40
```

**Comment by kixxauth** [comment]
How should the /config endpoint respond when the request has no channel or platform?

- 401 ?
- 404 ?

https://github.com/oddnetworks/oddworks/blob/master/lib/services/identity/controllers/identity-config-controller.js#L14-L45

**Comment by blainsmith** [comment]
Def 401

**Comment by blainsmith** [comment]
Actually it should never make it here if middleware is working properly and denying access up the chain.

**Comment by kixxauth** [comment]
An admin token (probably an API key given to another machine like the API service, or a 3rd party plugin) may not have a channel or platform associated with it.

In this case, I think the correct response should actually be 403 forbidden. As in "No, you will never have access to this resource given your token type."

**Comment by blainsmith** [comment]
That actually does make more sense given that possible scenario. A 401 means try again which won't help them.

**Comment by blainsmith** [comment]
Done.
