### ISSUE TITLE
PATCH /collectionSpecs/:id should take channel ID from request payload

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#174]
Currently this controller depends on the JWT or the `?channel=nasa` query parameter to get the channel ID. However, the channel ID should be a required attribute on the request payload at `data.attributes.channel`. If not present, a 422 should be returned.

https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/controllers/catalog-spec-controller.js#L57-L100

**Comment by kixxauth** [comment]
My earlier assessment that if a `data.attributes.channel` value is not present a 422 error should be returned is not not 100% correct.

If a channel ID is available on the JWT, it should be assigned to data.attributes.channel. If not, and if data.attributes.channel is not present, the controller should respond with a 422 error.

Solving #177 will fix this (dupe).

**Comment by aljachimiak** [comment]
This is was not addressed in #177 as there was logic present for this controller that was a bit different than the other controllers.

**Comment by aljachimiak** [comment]
Merged and Done.
