### ISSUE TITLE
All write endpoints should accept channel ID from JWT or request body

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#177]
## Expected Behavior
All writeable endpoints (POST | PATCH) should accept a channel ID from either the JSON Web Token or the request body (data.attributes.channel).

## Current Behavior
The JSON Web Token used by admin services typically does not have a channel or platform ID associated with it. In some (maybe all?) writable endpoints, if the JSON Web Token does not have a channel ID, the request fails with a 500:

```
TypeError: Cannot read property 'id' of undefined
        at CatalogListController.post (/node_modules/@oddnetworks/oddworks/lib/services/catalog/controllers/catalog-list-controller.js:38:41)
```

## Possible Solution
Use the channel ID from the JSON Web Token (from `req.identity.channel` in the controllers) when it is available, but accept the `data.attributes.channel` String as the channel ID if not on the JWT.

**Comment by kixxauth** [comment]
Additionally, if the object type being POSTed or PATCHed is not a "channel" then it MUST have an `data.attributes.channel` String, and that String must be a valid and existing Channel ID. ALL content in Oddworks is scoped to a channel, so this is required.

If a channel ID is available on the JWT, it should be assigned to `data.attributes.channel`. If not, and if `data.attributes.channel` is not present, the controller should respond with a 422 error.

**Comment by kixxauth** [comment]
In the oddworks authentication logic, it assumes that any JSON Web Token with a "admin" in the `audience` Array property is admin level, and is not required to have a channel or platform but MUST have a `subject` property on the JWT.

**Comment by blainsmith** [comment]
Yes to this. Even for `admin` tokens, why would it not have a channel in the JWT? Just a generic admin token to do anything?

**Comment by kixxauth** [comment]
Yeah, thinking through this some more. Here is the scenario:

- An admin service like a dashboard needs access to multiple channels
- It needs to create new channels
- It needs to modify existing channels
- It needs to create and modify platforms and content scoped to any channel

### 1. Require channel ID on the JWT and system admins create tokens
This means system admins will have to manually create new channels since the authentication system requires the channel to be present before it authenticates a JWT using a channel. System admins will then need to create new JWTs for the admins service to use on those channels.

The bad part about this is that no admin service would be able to dynamically create a channel.

### 2. Require channel ID on the JWT and admin service generates own tokens
This still means system admins will have to manually create new channels since the authentication system requires the channel to be present before it authenticates a JWT using a channel. However, after that is done, the admin service will be able to generate it's own tokens with the channel ID attached.

The bad part about this, is that the admin service will need the oddworks service server secret, and still rely on admins to manually create a new channel.

### 3. Require channel ID on the JWT and oddworks server has an endpoint to create a new JWT for a channel
An oddworks server could expose an endpoint which allows a calling service to create a new channel scoped JWT like POST `/tokens` or something. The oddworks server would still need a way to authenticate callers using this service. PV3 does it this way, and uses the oddworks JWT server secret to access this endpoint. This could be improved by giving out a special JWT to admin services with the `subject: "foo"` property (like oddworks does now), and including a white list of subjects which are allowed access to the `/tokens` endpoint. The same white list logic could be used in front of the POST/PATCH/GET `/channels` endpoint.

The [authentication middleware](https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/request-authenticate.js) would also have to be modified to allow a caller to have access to POST `/channels` even when the channel does not exist yet. This feature would allow the admin service to create a new channel using its new JWT, avoiding the need for a system admin to create new channels manually.

__OR__

The `/tokens` endpoint could automatically create a new channel when it is asked to create a token for which no channel exists yet. This would be much better.

### 4. Implement white listing in current authorization middleware
Oddworks could continue on as designed right now: Callers with a JWT `audience: ["admin"]` would be allowed access to any channel, or channel-scoped resource with read and write privileges. Currently any token created with `audience: ["admin"]` MUST also provide a `subject: "subjectId"` property. This subject property is designed to be used for white listing. 

To implement this, the current oddworks [authorization middleware](https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/request-authorize.js) needs to add to its whitelisting capability by also checking to make sure the subject is on a pre-configured white list if it is claiming that it is an admin JWT.

By using a white list, system admins can revoke compromised admin level JWTs. The white list would only contain a few allowed subject IDs at most.

**Comment by kixxauth** [comment]
I'm in favor of (4) above. It seems the least complicated to me.

**Comment by blainsmith** [comment]
Yes, 4 sounds like the best to move forward with.

**Comment by aljachimiak** [comment]
Merged and done.
