### ISSUE TITLE
Search and Store Patterns

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#185]
So while talking with @aljachimiak we found a bug in the communication between stores and search stores when performing a search.

`{role: 'catalog', cmd: 'search'}` calls `{role: 'store', cmd: 'query'}` which pulls results from the search store. When results are found the search store calls `{role: 'store', cmd: 'batchGet'}` to get the full objects for each result, however, that pattern does not exist. It should be `{role: 'store', cmd: 'batchGet', store: STORE_NAME}`.

The issue is that when a search store is initialized it needs to know which canonical store it needs to get the full objects from since you can set up multiple stores like DynamoDB and Redis in tandem. There is an issue with configuring these stores. There is a right way and a wrong way.

**Right Way**
```js
oddworks.stores.dynamodb(app.API.bus, {
  dynamodb: app.API.dynamodb,
  types: ['collection', 'collection']
}),
oddworks.stores.cloudSearch(app.API.bus, {
  cloudSearch: app.API.cloudSearch,
  types: ['collection', 'collection']
  canonicalStore: 'dynamodb'
}),
oddworks.stores.redis(app.API.bus, {
  redis: app.API.redis,
  types: ['channel', 'platform']
}),
oddworks.stores.redisSearch(app.API.bus, {
  redis: app.API.redisSearch,
  types: ['channel', 'platform']
  canonicalStore: 'redis-store'
})
```

This configuration could be borked by setting it up wrong. Do we care if someone does this?

**Wrong Way**
```js
oddworks.stores.dynamodb(app.API.bus, {
  dynamodb: app.API.dynamodb,
  types: ['collection', 'video']
}),
oddworks.stores.redis(app.API.bus, {
  redis: app.API.redis,
  types: ['channel', 'platform']
}),

// This configuration will index collection and video types, but try to get full objects from the wrong store above.
oddworks.stores.redisSearch(app.API.bus, {
  redis: app.API.redisSearch,
  types: ['collection', 'video']
  canonicalStore: 'redis-store'
})
```

How opinionated should we be? Being a platform we shouldn't, but we also don't want to completely overcomplicate an implementation as well. Thoughts?

@brkattk @kixxauth @pmcconnell

**Comment by brkattk** [comment]
Is there a way to get which stores have been initialized on a bus? In this case, initialization order may matter if we add checks and balances.

**Comment by blainsmith** [comment]
Initialization order has always mattered when stores must come before services, but initializing a search store before a main store would not matter.

I think oddcast offers a way to list which patterns have been registered to a bus, but it is not exposed in its API. https://github.com/oddnetworks/oddcast/blob/master/lib/pattern-matcher.js

**Comment by brkattk** [comment]
So when we pass a `canonicalStore` we can simply check to make sure it exists on the bus? That should be enough, really.

**Comment by blainsmith** [comment]
Yup, last bit is its not obvious at all what the store name is (ex. `redis-store`). It is exposed as `store.name` so it would really be,

```js
const dynamodb = oddworks.stores.dynamodb(app.API.bus, {
  dynamodb: app.API.dynamodb,
  types: ['collection', 'collection']
});
const cloudSearch = oddworks.stores.cloudSearch(app.API.bus, {
  cloudSearch: app.API.cloudSearch,
  types: ['collection', 'collection']
  canonicalStore: dynamodb.name
});
const redis = oddworks.stores.redis(app.API.bus, {
  redis: app.API.redis,
  types: ['channel', 'platform']
});
const redisSearch = oddworks.stores.redisSearch(app.API.bus, {
  redis: app.API.redisSearch,
  types: ['channel', 'platform']
  canonicalStore: redis.name
});
```

We could take this a step further and really depend on main stores for search since in reality they do. Here we initialize the main stores first and pass the instances of them into the search stores. The search stores can then use the `name` and `types` to do their work. So in essence a search store **requires** a main store instance.

```js
Promose.join(
  oddworks.stores.dynamodb(app.API.bus, {
    dynamodb: app.API.dynamodb,
    types: ['collection', 'collection']
  }),
  oddworks.stores.redis(app.API.bus, {
    redis: app.API.redis,
    types: ['channel', 'platform']
  }),
  (dynamodb, redis) => {
    return Promise.join(
      oddworks.stores.cloudSearch(app.API.bus, {
        cloudSearch: app.API.cloudSearch,
        store: dynamodb
      }),
      oddworks.stores.redisSearch(app.API.bus, {
        redis: app.API.redisSearch,
        store: redis
      })
    );
  });
```

**Comment by brkattk** [comment]
I read your first chunk of code, and then wrote the same thing you wrote for the second chunk of code.

:+1:

**Comment by blainsmith** [comment]
Great minds.
