### ISSUE TITLE
Response json api needs to handle empty response

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#187]
When fed an empty array the `response-json-api` middleware errors out and causes a `500` response to be sent to the client.

## Expected Behavior
If an Empty array is passed to the `response-json-api` middleware, a well-formed response should be output.

## Current Behavior

Currently, oddworks is relying on a type argument from the first element in the array to get a type.  When the array is empty this causes an unhandled error.

**Comment by brkattk** [comment]
Does #188 fix this?
