### ISSUE TITLE
/collections includes entities relationship by default

### ISSUE THREAD

**Issue by pmcconnell** [oddnetworks/oddworks#189]
I am assuming this a bug.

/collections/<id> will return a response with relationship->entities data included as if the request was written with the include query string.

If this is the intended default behavior, the response is not filtered for errors (i.e. incorrect entity data) in the same manner as ?include= requests are processed.

Discovered this by hitting /collections/<id>?include=entities and getting entities = []
removing the query string returned the expected, though incorrect, entity data.

**Comment by pmcconnell** [comment]
upon reflecting the relationship data should be there its the included objects that are the issue. 

still its not behaving the same as when ?include=entities is specified. One returns [] and the default populates the relationship

**Comment by brkattk** [comment]
IMO if we don't have anything in `?include={rel name}` then the response should not have `included` in it

**Comment by brkattk** [comment]
To be clear @pmcconnell, when you hit:
`/collections?include=entities`
you get:
```
{
  "data": {
    // ...
    "relationships": {
      "entities": {
        "data": []
      }
    }
  },
  "included": []
}
```

but when you hit:
`/collections`
you get:
```
{
  "data": {
    // ...
    "relationships": {
      "entities": {
        "data": [
          {"id": "123", "type": "video"},
          // ...
        ]
      }
    }
  },
  "included": [{actual entity}, ...]
}
```

This is a bug.

- [ ] remove "included" from response when using the bare `/collections` endpoint (or any endpoint without the `include` parameter
- [ ] do not remove "relationships.{any}.data"

**Comment by pmcconnell** [comment]
yes that clarification is correct

my original comments regarding the relationship stuff being included by default being a bug is incorrect. relationships should always(?) be there. Included should be optional

**Comment by aljachimiak** [comment]
To clear up the above comments...

We're actually looking at `/collections/:id` for a specific collection, rather than `/collections` for all collections.

**Comment by pmcconnell** [comment]
correct

assuming /collections is using the same methods as /collection/:id any changes you make may end up having an effect on /collections. buy you know that

**Comment by aljachimiak** [comment]
> /collections/ will return a response with relationship->entities data included as if the request was written with the include query string.

When corrected to `/collections/:id`, this is a correct response.  All responses for a single collection should should have a `obj.relationships.entities.data` present.  It may be a single `{}` or many obj in an Array (`[{}, {}, {}]`), but it should be there.


>If this is the intended default behavior, the response is not filtered for errors (i.e. incorrect entity data) in the same manner as ?include= requests are processed.

The difference here is that when `?include=entities` is present, the object will come back with an additional prop of an included array or `obj.included = []`.  


>Discovered this by hitting /collections/?include=entities and getting entities = [] removing the query string returned the expected, though incorrect, entity data.

This is Issue #160 working correctly.  If the entities are not actually present in the db, they will:
- for `/collections/:id?include=entities`
    - not show up in the included array
    - _also_ be removed from the `obj.relationships.entities.data`
- for `/collections/:id` without the query string
    - the `obj.relationships.entities.data` will appear as it appeared when inserted into the db
    - the above holds true, even if the listed entity is absent from the db.

**Comment by blainsmith** [comment]
Done.
