### ISSUE TITLE
Caching logic get's unexpected Boolean result if resource is not found

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#194]
This bug was picked up off a stack trace from a production server.

## Current Behavior
The resource returned by `checkCache()` in [services/catalog/queries/index](https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L81) is sometimes a Boolean or otherwise an object which results in this error:

```
TypeError: Cannot assign to read only property 'meta' of true
    at /opt/oddworks/node_modules/@oddnetworks/oddworks/lib/services/catalog/queries/index.js:84:22
```

This is most likely due to the fact that [removeItem() returns a Boolean](https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L209-L212).

## Possible Solution
Wrap the call to removeItem() to always return an Object in [services/catalog/queries/](https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L209-L212):

```js
// If the spec didn't exist, or the object did not exist at the source,
// then remove it from the store.
return service.bus.sendCommand(
  {role: 'catalog', cmd: 'removeItem', type},
  object
).then(_.constant(object));
```

**Comment by aljachimiak** [comment]
Looks like this was merged at #196.


Closing.
