### ISSUE TITLE
4xx Caching

### ISSUE THREAD

**Issue by genexp** [oddnetworks/oddworks#2]
We need to make sure any 4xx response is cached.  If it's content related, it should be a long(er) cache, if its auth related, it should be shorter.  We need to make sure this doesn't break auth api.

**Comment by genexp** [comment]
@kixxauth @tquackenbush Copying you here.

**Comment by genexp** [comment]
![screen shot 2016-03-07 at 9 35 03 pm](https://cloud.githubusercontent.com/assets/816/13590865/921275cc-e4b1-11e5-8b05-5c7ec209c974.png)

**Comment by blainsmith** [comment]
See #6
