### ISSUE TITLE
Admin GET of lists of items

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#203]
An Admin token should be able to GET a list controller by specifying a channelId on the query.  [Currently this is only possible on a get of a catalog item.](https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/controllers/catalog-item-controller.js#L30-L38)

## Possible Solution
(1) For each of the list endpoints, an admin should be able to fetch a list of items or identity items for any channel by specifying a channelID on the query.
(2) Each of these endpoints should be tested.  [Placeholders for these tests already exist](https://github.com/oddnetworks/oddworks/blob/master/spec/services/catalog/controllers/admin-catalog-list-controller-spec.js#L151-L153).

**Comment by kixxauth** [comment]
Done in #234
