### ISSUE TITLE
Admin DELETE of items

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#204]
Currently any JWT can DELETE an item by providing a `payload.channel` on the body of the request.  Most likely, a DELETE request should only be allowed from:

1. an admin token
2. a token with an identity on the actual channel

## Possible Solution

1. `.deleteFetchChannel()` need to be implemented in the [generic controller](https://github.com/oddnetworks/oddworks/blob/master/lib/controllers/controller.js#L79-L81), do that an admin token can specify a channel on the query.
2. the DELETE endpoints need to be modified to use `.deleteFetchChannel()`
3. the DELETE endpoint should be tested.  [Placeholders exist for these test already](https://github.com/oddnetworks/oddworks/blob/master/spec/services/catalog/controllers/admin-catalog-item-controller-spec.js#L203-L205).

**Comment by aljachimiak** [comment]
@kixxauth ->  Please comment on this.  I think you mentioned that this hasn't been implemented yet.

Right now it looks like that the channel can be specified in the payload of the delete request.
````javascript
delete(req, res, next) {
		const type = this.type;
		const payload = req.body;
		const channel = payload.channel || (req.identity.channel || {}).id;

		if (type !== 'channel' && !channel) {
			return next(Boom.badData('"channel" is required'));
		}
````

Am I ok to change this to specifying the `req.query.channel` for the ID?  Or should this stay as the `payload.channel` as the way an admin specifies a channel?

Thanks

**Comment by kixxauth** [comment]
yeah, bring the DELETE implementation up to speed @aljachimiak 👍 

It was "implemented" but I don't think it's ever been used or tested.

**Comment by kixxauth** [comment]
Done in #234
