### ISSUE TITLE
Filter out "searchable" attribute

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#208]
Resources where the data have been marked as searchable in the data store are presenting this attribute to end-users.

## Expected Behavior
Only show specified resource attributes.

## Current Behavior
Showing unspecified attributes.

## Possible Solution
Whitelist attributes per resource type?

## Steps to Reproduce (for bugs)
GET a collection, video, etc that has been marked `searchable`

**Comment by blainsmith** [comment]
How about standardizing on a `meta.internal` key that we can do back-end logic on, but it gets stripped before being sent to the SDKs?

**Comment by aljachimiak** [comment]
FYI - this is happening only on the list endpoint, not on the item endpoints.

**Comment by aljachimiak** [comment]
@brkattk -> is bug specific to content-service?

**Comment by brkattk** [comment]
Yes
