### ISSUE TITLE
Single Click Install Issues

### ISSUE THREAD

**Issue by pmcconnell** [oddnetworks/oddworks#21]
Now that the server will get up and running with no dependencies the following issues remain:

- Attempting to fetch a view via the provided curl command or postman will result in a error on serializing a null object. 

I traced the problems origin(?) to json-api/index.js in the services.middleware method. The server response (res) being processed has no body and the cloneDeep on line 22 results in data being undefined. 

Once this data is passed to be serialized on line 27 the server will error: 
TypeError: Cannot set property 'attributes' of undefined

The actual error (500) will come after line 53 in the serialize method

edited to remove 'crash' it drops a 500 error

**Comment by pmcconnell** [comment]
ok its a simple fix. don't post to the videos route. Postman was inadvertently set to POST rather than GET. Perhaps we can handle this one better?

**Comment by blainsmith** [comment]
Still an issue tho. It should have responded with a 404 and not exploded with a 500.

**Comment by pmcconnell** [comment]
agreed but not quite as serious. I am seeing the correct response when I ask nicely

**Comment by pmcconnell** [comment]
Next one

- The readme mentions a CLI command for getting help for things like generating tokens. It implies one can just type `oddworks --help` to see a list of allowable commands. Typing this will result in command not found. 

More information or fix is required

**Comment by pmcconnell** [comment]
- The server provides a route at '/' to simply indicate the server is running. While not the most fascinating piece of information it is useful as a simple check. 

This route is not reachable. A request to '/' times out.

**Comment by pmcconnell** [comment]
CLI is working correctly after running `npm setup` as instructed in revised readme.

- `CLI --help` could use further explanation on what the two token types are, how they are used and what the params are.

**Comment by pmcconnell** [comment]
The '/' route is now working. Should we consider exempting this one from needing an auth token?

**Comment by barthdamon** [comment]
no harm in letting people play ping pong

**Comment by pmcconnell** [comment]
- remove unnecessary dependencies

Of particular interest would be removing mongo since it throws a warning on install/setup

**Comment by pmcconnell** [comment]
- clarify curl example requires correct auth token -or- provide a token that will work.

currently copy pasta of the curl command will return invalid token error. So yes the server is running but no its not nice

**Comment by pmcconnell** [comment]
- clarify what network & device types/strings are acceptable when generating token with CLI

Its not immediately apparent from the online help what a 'network' is or what a 'device' string can be. Is the user limited to certain device strings?

**Comment by pmcconnell** [comment]
- error on listing videos after token generation

steps to reproduce.

- do the install/setup dance with a fresh clone of odd works
- run `oddworks generate-token -n foobar -d apple-tv` from CLI
- insert generated token into sample curl command:

`curl -X GET -H "x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJuZXR3b3JrIjoiZm9vYmFyIiwiZGV2aWNlIjoiYXBwbGUtdHYiLCJzY29wZSI6WyJkZXZpY2UiXSwiaWF0IjoxNDYwNjQ1NzAyfQ.jp7QsQ-au1PTvw0EimyAbIrqWY_RYbW8lMvU8mBB140" -H "Accept: application/json" -H "Cache-Control: no-cache" "http://localhost:3000/videos"`

- server will error with:

`Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at /Users/patrickmcconnell/Documents/Source/MadGlory/oddworks/services/identity/index.js:27:21`

**Comment by blainsmith** [comment]
Wonder if these should start being separate issues now? Otherwise this issue will never close.

**Comment by pmcconnell** [comment]
I will review and create new issues for each

**Comment by blainsmith** [comment]
Kewl. Can "label" them as 2.0.0 or whatevers.

**Comment by pmcconnell** [comment]
new individual issues created with `oddworks 2.0.0` tag.

closing
