### ISSUE TITLE
/resourceType/resourceId/relationships/relationshipKey should always return an array, even when blank

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#216]
Currently getting the following response from this endpoint

`/resourceType/resourceId/relationships/relationshipKey`

``` json
{
  "data": {},
  "meta": {
    "channel": "mychannel",
    "platform": "ANDROID"
  }
}
```
## Expected Behavior

`.data` should never be an object `{}`, it should always be an Array `[]`
## Current Behavior

`.data` is `{}`
## Steps to Reproduce (for bugs)

Talk to @brkattk for call on our server
## Context

SDKs expect this to be a list endpoint, so some parsers will fail here.

**Comment by aljachimiak** [comment]
I think PR #212 will address this.

I believe that it would be appropriate to add in an empty array as a test case for this endpoint as well.

**Comment by aljachimiak** [comment]
In fact, you may have reproduced #210 when you found this.

**Comment by aljachimiak** [comment]
Done!
