### ISSUE TITLE
Issues with admin channel-list

### ISSUE THREAD

**Issue by aljachimiak** [oddnetworks/oddworks#219]
I've observed some possible issues in the identity-list-controller.

They can be seen in this [branch here with inline code comments](https://github.com/aljachimiak/oddworks/commit/87c2478e484726e19a3ba47a88136010ae479d53).

## Expected Behavior
1. POST of a new channel should keep the id that is in the body of the request.
2. ~~GET of the channel list should be (maybe) restricted to an admin token.~~ 
3. GET of the channel list, since it _should_ return all the channels, should not need a channel specified from the token, or anywhere else in the request because it is a channel agnostic response.

## Current Behavior
1. POST of a channel, with an admin token, seem to be generating a random id (found in test specs).
2. GET of the channel list pulls the channel from the token identity or a query param (for admin).  This seems to be returning only the channel that is found on the token or provided on the query of the request.

## Steps to Reproduce (for bugs)

Try pulling down the branch mentioned at the top of this issue.  These issues are noted inline and have tests setup for them

## Context

These were found while refactoring out the channelFetching logic from the identity-list-controller.

**Comment by blainsmith** [comment]
Ah. Yeah a channel ID should always be supplied and never generated.

**Comment by aljachimiak** [comment]
>GET of the channel list should be (maybe) restricted to an admin token.

Looks like all identity endpoints are [restricted to admin tokens in the router.](https://github.com/oddnetworks/oddworks/blob/master/lib/services/identity/index.js#L66-L83)

**Comment by kixxauth** [comment]
Cool. Addressing these in the controller workover.

**Comment by kixxauth** [comment]
Addressed in #234
