### ISSUE TITLE
channel.features > platform.features > resource.meta.features merging

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#230]
Currently I am not seeing `video.meta.features` when the data store has the following:

**Channel**
```js
{
  // ..
  "features": {
    "sharing": {
      "enabled": true,
      "text": "Generic sharing message for channel-wide default"
    },
    // ..
  }
}
```

**Platform**

I've tried no sharing feature at all, as well as the following:

```js
{
  // ..
  "features": {
    "sharing": {
      "enabled": true
    },
    // ..
  }
}
```

**Video**

There isn't anything on the video resource to override platform or channel features.

## Expected Behavior

Features should be merged using the following strategy:

- DEFAULT_FEATURES 
```js
{
  "ads": {
    "enabled": false
  },
  "authentication": {
    "enabled": false
  },
  "metrics": {
    "enabled": false
  },
  "sharing": {
    "enabled": false
  }
}
```
- individual channel features override above
- individual platform features override above
- individual resource features override above

## Current Behavior

The above logic does not seem to work properly.

## Context

This needs to work ASAP due to client launch implications.

**Comment by blainsmith** [comment]
The culprit is actually over here: https://github.com/oddnetworks/odd-content-service/blob/master/lib/strict-transform.js#L109

In oddworks tho we do whitelist `'ads', 'player', 'sharing', 'overlay'`. Auth and metrics are not let through onto the resources.

**Comment by blainsmith** [comment]
Fixed in https://github.com/oddnetworks/odd-content-service/commit/582ae589f7b206e3355e7c03c20ef189201887b2#diff-5854963509d40abb852a8584b8243d0a
