### ISSUE TITLE
`view` Patterns Mistaken for `viewer` Patterns

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#238]
## Expected Behavior

Should not match patterns for `view`.
## Current Behavior

Unless the server implements the stores right with the correct resource there are cases where `view` is mistake for `viewer`. Mainly in `/config` it will make a new anon-view instead of anon-viewer.
## Possible Solution

Not actually sure yet.
## Steps to Reproduce (for bugs)
1. Do not define `viewer` as a type in the stores, but define `view`.
2. Hit `/config` and it will generate an anon-view, but should throw an error for missing pattern.
## Context

Pollutes the `view` table with blank unused views.

**Comment by aljachimiak** [comment]
Was bloom in odd cast a way to address this?

**Comment by blainsmith** [comment]
We thought it was, but it was still happening until I updated content service with the right types.

**Comment by blainsmith** [comment]
We tracked down this issue and it was actually fixed.
