### ISSUE TITLE
dynamodb-marshaler does not allow empty strings

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#243]
Since DynamoDB does not take empty strings, the developers of dynamodb-marshaler decided to honor this by throwing a TypeError when an empty string is encountered. See [this issue on dynamodb-marshaler](https://github.com/CascadeEnergy/dynamoDb-marshaler/issues/21) - one of the comments mentions using the native [AWS DocumentClient](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html)

This will bite us (and is currently via the brightcove provider) because we can't guarantee the values of things like descriptions/titles/etc.

Here's where this is used:
https://github.com/oddnetworks/oddworks/blob/master/lib/stores/dynamodb/index.js

**Comment by kixxauth** [comment]
dynamodb-marshaler is wreaking havoc in the system in general. Spotted this one today:

```
TypeError: Encountered unexpected item\n at Array.unexpectedItemHandler (/app/node_modules/dynamodb-marshaler/lib/unexpectedItemHandler.js:4:9)\n at fn (/app/node_modules/dispatch-recursive/index.js:22:27)\n at /app/node_modules/lodash/lodash.js:13047:23\n at /app/node_modules/lodash/lodash.js:4738:15\n
```
