### ISSUE TITLE
/:resourceType/:id?include=:rel1,:rel2 fails if one relationship doesn't exist

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#246]
We're making a request like:

`/collections/collection-id?include=featured,entities` 

Only the `entities` actually exists on this collection, but it causes a 500 error resulting in this response:

```
{
  "errors": [
    {
      "status": "500",
      "title": "TypeError",
      "detail": "Cannot read property 'id' of undefined"
    }
  ]
}
```

I think this might be happening because of this line:

https://github.com/oddnetworks/oddworks/blob/master/lib/middleware/response-json-api.js#L213

We need to allow requests for any relationship, but only throw errors if the relationship exists and a referenced resource identifier within is not found. Otherwise we should be able to request `?include=doesntexist,notreal` and just return `included: []` on the response (or only fill that array with fulfilled relationship results.

**Comment by aljachimiak** [comment]
Done!
