### ISSUE TITLE
/search resource type filtering should be done using `types` not `type`

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#258]
I think this line is wrong:

https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/controllers/catalog-search-controller.js#L17

It's sending the `type` option to the query, but should actually be `types`, an array of type strings, according to lib/stores/README.md

**Comment by blainsmith** [comment]
It is actually `type` being used in the store search patterns. We can change it to `types` though.

**Comment by brkattk** [comment]
the query param `types` makes more sense if we're expecting comma-separated string to be parsed into an array
