### ISSUE TITLE
Error on listing videos after token generation

### ISSUE THREAD

**Issue by pmcconnell** [oddnetworks/oddworks#27]
- error on listing videos after token generation

steps to reproduce:

do the install/setup dance with a fresh clone of odd works
run oddworks generate-token -n foobar -d apple-tv from CLI
insert generated token into sample curl command:
curl -X GET -H "x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJuZXR3b3JrIjoiZm9vYmFyIiwiZGV2aWNlIjoiYXBwbGUtdHYiLCJzY29wZSI6WyJkZXZpY2UiXSwiaWF0IjoxNDYwNjQ1NzAyfQ.jp7QsQ-au1PTvw0EimyAbIrqWY_RYbW8lMvU8mBB140" -H "Accept: application/json" -H "Cache-Control: no-cache" "http://localhost:3000/videos"

server will error with:
Unhandled rejection TypeError: Cannot read property 'length' of undefined at /Users/patrickmcconnell/Documents/Source/MadGlory/oddworks/services/identity/index.js:27:21

**Comment by pmcconnell** [comment]
This one may be a matter of my assuming it worked differently.

My assumption was the tool would generate the token and create the required store entries. It currently only creates the token and reports it to the user.

We should either improve the tool to create the required db entries or at a minimum document the entries to be created manually.

**Comment by blainsmith** [comment]
No it literally generate a token for the given PRE-EXISTING network and device within the db. The next iteration would be actually manipulate data if we wanted, but ultimately that is what the dashboard is for.

**Comment by pmcconnell** [comment]
So if I understand it correctly you would use the CLI tool to generate the token and copy pasta it into the device entry that already exists. 

The network/device params map to the ids of these records?

The remaining pain points will be that it does no validation and errors will not be obvious to the user.

**Comment by blainsmith** [comment]
The generated JWT is never stored in the db it would be used in the apps. Idea is to have all your data set up and then generate tokens with all the data set up.

Yes the params are network id and device id of pre-existing records. We can clear up these instructions to set the correct expectations. Perhaps a README in the `/cli` directory.

**Comment by pmcconnell** [comment]
right sorry. wrong jwt.

**Comment by pmcconnell** [comment]
I think https://github.com/oddnetworks/oddworks/commit/406787930343baff327f764d47f416da434c927f helps clarify this. You can review and close if you agree.

**Comment by blainsmith** [comment]
Use the right token and this works.
