### ISSUE TITLE
MongoDB Connection Settings

### ISSUE THREAD

**Issue by genexp** [oddnetworks/oddworks#3]
We need to triple check the mongodb connection settings for sanity and write up some suggestions on what they should be (or update the defaults).

  http://mongodb.github.io/node-mongodb-native/2.1/api/Server.html#event:timeout

**Comment by blainsmith** [comment]
Yeah we have stuff in the config already, but we can document this a lot better.

https://github.com/oddnetworks/oddworks/blob/master/config.js#L49-L59

**Comment by blainsmith** [comment]
Since we moved to Redis this is no longer an issue. Oddworks 2.0 with be optimized for read speed.
