### ISSUE TITLE
ReadMe file outdated?

### ISSUE THREAD

**Issue by indieocean** [oddnetworks/oddworks#33]
It seems that the ReadMe file is outdated to anything related to oddchannels.

https://github.com/oddchannels/oddworks-ios-tvos-sdk
https://github.com/oddchannels/oddworks-android-sdk

Roku SDK is coming soon but in the site it appears as supported.

**Comment by pmcconnell** [comment]
So funny story....
There is no odd channels. That is the result of an overzealous find -> replace all for the word 'networks'

Thanks for pointing these out. Will fix 'em shortly
