### ISSUE TITLE
YouTube Sync Provider

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#40]

**Comment by pmcconnell** [comment]
I did some reading on this one and I think its most likely very difficult to comply with YouTubes terms of service. They all but rule out non-youtube players. We may be able to sync some data but usage would probably be limited, difficult or non-conforming to their terms

https://developers.google.com/youtube/terms?hl=en

**Comment by kixxauth** [comment]
Yeah, I had a feeling that would be the case.
