### ISSUE TITLE
Release Flow

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#56]
Since we are now publishing Oddworks to npm as a package we should come up with a plan for releasing it. Ideally it would be as simple as when we think its ready we can create a release in GitHub, which creates a tag, and then it auto-publishes to npm with the right tag number. The issue is we need to make sure the package.json version match the GitHub tag.

There might be a way helpful way to have a command `npm run publish` which does all the magic since `npm publish` does not do anything other than try to push it to npm. It doesn't auto-increment version, commit, tag, then push to GitHub.

**Comment by kixxauth** [comment]
This would be awesome.

Anyone opposed to a bin/ folder in the root of the repo where scripted tooling can live?

**Comment by brkattk** [comment]
That sounds helpful
