### ISSUE TITLE
Cache Hit Ratio

### ISSUE THREAD

**Issue by genexp** [oddnetworks/oddworks#6]
One of the two builds we did today broke our cache.  At least, we're caching about 50% fewer items than we were today.  Odds are we forgot to return a cache-header on something.  

- [ ] We need to return a cache header on *every* response, 5xx, 4xx, etc.  Our vary headers right now ensure that this works correctly. 
- [ ] We need to figure out the specific regression that broke our HTTP cache today.  We've doubled our origin traffic which requires additional servers.

/cc: @kixxauth @cforbes 

![screen shot 2016-03-08 at 9 23 07 pm](https://cloud.githubusercontent.com/assets/816/13623406/73505686-e574-11e5-8ef7-85364b059e6a.png)

**Comment by blainsmith** [comment]
I think we got this figured out after a week of high traffic.
