### ISSUE TITLE
Using query params collections should support sort (field + direction)

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#63]
How does sorting fit into JSON API spec? Is it even mentioned in JSON API, or should we define it here?

**Comment by brkattk** [comment]
[http://jsonapi.org/format/#fetching-sorting](http://jsonapi.org/format/#fetching-sorting)

**Comment by kixxauth** [comment]
Merging these two issues into one: https://github.com/oddnetworks/oddworks/issues/64
