### ISSUE TITLE
Using query params, collections should support sort, filter, and paging

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#64]
Using query params, all collections should support paging (offset, count per 
page) and return of total count.

Is this defined in JSON API spec, or should we define it?

**Comment by brkattk** [comment]
[http://jsonapi.org/format/#fetching-pagination](http://jsonapi.org/format/#fetching-pagination)
[http://jsonapi.org/format/#fetching-filtering](http://jsonapi.org/format/#fetching-filtering)

**Comment by pmcconnell** [comment]
I think the spec has spoken

**Comment by kixxauth** [comment]
Talked this over with @brkattk and @blainsmith today and came to the conclusion that the way sort, filter, and pagination should be implemented for Oddworks collections is by using the JSON API relationships query: http://jsonapi.org/format/#fetching-relationships

The problem we have, is that Oddworks needs to present *ordered lists* of content, which are *named* (usually via a unique ID). These ordered lists are called "collections" within Oddworks. JSON API provides a specification for querying collection endpoints (where collection is an endpoint that return lists of data like `data: []`, but we're on our own when it comes to filtering, sorting, and limiting Oddworks collections.

However, @brkattk had a brilliant idea of using the spec for fetching relationships (see the link above). It would work like this:

`GET /collections/my-collection-id/relationships/entities?sort=title&limit=7`

**Comment by brkattk** [comment]
The route for fetching a relationship would be like:

`GET /{resourceType}/{resourceId}/relationships/{relationshipKey}`

I believe we did (maybe we still do) add the link for this within the `relationships.{key}.links`

As for pagination, the spec says to use the `page` query parameter and can be implemented in many ways, but we should probably use an offset/limit strategy like `page[offset]=40&page[limit]=20`

http://jsonapi.org/format/#fetching-pagination

**Comment by aljachimiak** [comment]
I'd like to forge ahead on this, but there are some questions:
 - `page[offset]` with no `page[limit]`:  What should be the default `limit`?
 - `page[limit]` with no `page[offset]`:  I'd assume a default `offset` of 0 (or page 1)
 - naming things... using brackets may get messy on the backend:
````javascript
const req = {
			...
			query: {
				sort: 'title',
				'page[offset]': 1,
				'page[limit]': 3
			},
            ...
        };
````

**Comment by brkattk** [comment]
The default limit should be 10. Express should parse those params nicely on the back end so you should get `query.page.limit`. We should also send back the default values even if they aren't set. Meaning if they give only a limit or only an offset, we should send both back.

**Comment by aljachimiak** [comment]
After clarification from @brkattk , I'll pull the included out of this code.

**Comment by blainsmith** [comment]
@aljachimiak We can close this right?

**Comment by blainsmith** [comment]
Done.
