### ISSUE TITLE
Investigate Clustering for Production

### ISSUE THREAD

**Issue by genexp** [oddnetworks/oddworks#7]
It's relevant everywhere, but here's the article on Heroku.
    https://devcenter.heroku.com/articles/node-concurrency

**Comment by kixxauth** [comment]
:+1: Reading now. I didn't even know Heroku had a way to do clustering, or that it was even worthwhile on a dyno

**Comment by genexp** [comment]
Even better, it's now done! We need to pull it into this repo tho.

**Comment by kixxauth** [comment]
Cool!

(still need to make sure I undertand how it works ;-)

**Comment by blainsmith** [comment]
We have clustering support in our hosted version with https://www.npmjs.com/package/throng and it was easy to implement if others need it.
