### ISSUE TITLE
Quickstart / Requirements Docs

### ISSUE THREAD

**Issue by chiefy** [oddnetworks/oddworks#8]
There's a few people in slack who seem confused on how to get things up and running. It would be helpful to have a quickstart or a tutorial on how to quickly get things up & running. Possible topics:

- Local setup w/ Vagrant
- Local setup w/ Docker
- Deploy to AWS / Heroku / DigitalOcean (see-also #7 )
- Troubleshooting
- Resource requirements

**Comment by blainsmith** [comment]
Also add some time to sweep through the tests and make sure seed data is up to date for a good experience.

**Comment by blainsmith** [comment]
Also add a 30,000 ft view of the entire architecture to explain how things interact.

**Comment by clarkefoley** [comment]
Future Oddworks architecture:
https://docs.google.com/drawings/d/1Jdpn17ijuBBBW-o-u9veiNRLGoQXKz8nyMaVqnO-kIU/edit
Ahoy great guys, maybe some of these are usable or helpful? 

Current Oddworks architecture: 
https://docs.google.com/drawings/d/1WbTy5sW7Gr-j410fcL0kHbpXVQJyzezIwQnLYajoG08/edit

See snazzy diagram that Corrigan drew this week in NYC for reference maybe? 

<img width="921" alt="screenshot 2016-03-11 11 00 56" src="https://cloud.githubusercontent.com/assets/427972/13707647/a56eb3b4-e778-11e5-856f-50da0c5398cf.png">

**Comment by blainsmith** [comment]
Easier setup with 2.0.0 now.
