### ISSUE TITLE
Refuse access to any resource if the platform or channel have active:false

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#85]
Allow admins to disable a channel or platform.

## Expected Behavior
If a channel or platform object has the `active` member set to `false`, then requests containing a JWT referencing that channel or platform should respond with a 403 Forbidden status.

## Current Behavior
`channel.active` and `platform.active` are ignored.

**Comment by blainsmith** [comment]
Also noting in the open that any store get/set should require `channel` be set for multi tenancy and memory optimizing or at least be scoped to a channel.
