### ISSUE TITLE
Break out seneca-odd-events

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#9]
Break out seneca-odd-events into it's own repository, much like https://github.com/oddnetworks/seneca-odd-entitlement

Being able to break out providers to their own file would be handy, as well

**Comment by genexp** [comment]
I think we should consider no longer using Seneca period (though keeping a few of the patterns).

Initially we were optimizing for a scalable microservice platform, but now we're optimizing for low cognitive load.  We aren't typically operating backends for people anymore, and if we do, we wouldn't operate a single platform.  Seneca isn't adding much but complexity, and it makes the interface between modules limited to whatever can go over it's gate executor.  Namely, functions that return a single object.  If we could return promises (or even richer callbacks) a lot would be easier.

Also, I don't think events should be a seneca module.  Why would we ever want to access it via network transport?

**Comment by brkattk** [comment]
I just meant break it (or maybe just it's providers) out of the api.
Currently the file is called `seneca-odd-events` so that's why this issue
has that name. I have no opinion on whether to use seneca or not.

**Comment by kixxauth** [comment]
Yeah, I'm +1 on moving away from Seneca (personally I like [Oddcast](https://github.com/oddnetworks/oddcast), for keeping the good concepts of Seneca, but in a more transparent and manageable way).

I'm not sure we need to separate events into a plugin or module. I *do* think it should be able to be configured separately.

**Comment by brkattk** [comment]
I created this issue because I noticed how entitlement services was broken up a bit (main file for the actual entitlement module, individual files per entitlement provider). I figured it would be best if we did the same for event providers as well, rather than have an ever-expanding class as we (or others) implement new providers for metrics (currently there are 2 and they're both within the seneca-odd-events.js file, which should be renamed)

**Comment by blainsmith** [comment]
I think we all agree that we are going to standardize on some sort of plugin system to make this easy to stitch the platform together. Continue over here #13
